# Generated by Django 5.2.3 on 2025-07-10 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PasswordReset',
            new_name='PasswordResetToken',
        ),
    ]
