# Generated by Django 5.2.3 on 2025-07-02 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Horde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('greatkhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hordes', to=settings.AUTH_USER_MODEL, verbose_name='greatkhan')),
            ],
        ),
        migrations.CreateModel(
            name='Tent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('horde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tents', to='hordes.horde', verbose_name='horde')),
            ],
        ),
    ]
