# Generated by Django 5.2.3 on 2025-07-07 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hordes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('tent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='hordes.tent')),
            ],
            options={
                'unique_together': {('tent', 'username')},
            },
        ),
    ]
