# Generated by Django 5.2.3 on 2025-07-11 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hordes', '0002_tentparticipant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tentparticipant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tentparticipant',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to=settings.AUTH_USER_MODEL, verbose_name='user'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='tentparticipant',
            name='username',
        ),
    ]
