# Generated by Django 5.2.3 on 2025-07-11 06:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hordes', '0003_alter_tentparticipant_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tentparticipant',
            unique_together={('tent', 'user')},
        ),
    ]
